import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1752793516193 implements MigrationInterface {
    name = 'InitialMigration1752793516193'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "email" varchar(255) NOT NULL, "fullName" varchar(100) NOT NULL, "phone" varchar(20), "avatarUrl" varchar(500), "passwordHash" varchar, "isEmailVerified" boolean NOT NULL DEFAULT (0), "isPhoneVerified" boolean NOT NULL DEFAULT (0), "status" varchar(20) NOT NULL DEFAULT ('active'), "oauthProvider" varchar(50), "oauthProviderId" varchar(255), "preferredLanguage" varchar(5) NOT NULL DEFAULT ('en'), "timezone" varchar(50) NOT NULL DEFAULT ('UTC'), "notificationPreferences" text NOT NULL DEFAULT ('{"email":{"courseUpdates":true,"reminderNotifications":true,"achievementAlerts":true,"weeklyProgress":true},"sms":{"reminderNotifications":false,"urgentUpdates":false},"push":{"lessonReminders":true,"quizAvailable":true,"achievementUnlocked":true}}'), "hasCompletedOnboarding" boolean NOT NULL DEFAULT (0), "isFirstLogin" boolean NOT NULL DEFAULT (1), "lastActiveAt" datetime, "lastLoginAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f169d18dc7fce81f4c20974fd0" ON "users" ("phone") WHERE phone IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "course_enrollments" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "courseId" varchar NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('active'), "enrollmentMethod" varchar(20) NOT NULL DEFAULT ('self'), "progressPercentage" decimal(5,2) NOT NULL DEFAULT (0), "lessonsCompleted" integer NOT NULL DEFAULT (0), "totalLessons" integer NOT NULL DEFAULT (0), "timeSpentMinutes" decimal(10,2) NOT NULL DEFAULT (0), "lastAccessedLessonId" varchar, "currentLessonId" varchar, "isCompleted" boolean NOT NULL DEFAULT (0), "completedAt" datetime, "finalScore" decimal(5,2), "isCertificateEligible" boolean NOT NULL DEFAULT (0), "certificateIssuedAt" datetime, "paymentStatus" varchar(20) NOT NULL DEFAULT ('free'), "paymentAmount" decimal(10,2) NOT NULL DEFAULT (0), "paymentCurrency" varchar(3) NOT NULL DEFAULT ('USD'), "paymentTransactionId" varchar, "expiresAt" datetime, "accessNotes" text, "lastActivityAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "startedAt" datetime, "suspendedAt" datetime, "droppedAt" datetime, CONSTRAINT "UQ_03317be27c60a610b6a28795525" UNIQUE ("userId", "courseId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ab72c7fa06784137e905f1f8b8" ON "course_enrollments" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d77e489db35c7d325700d799be" ON "course_enrollments" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e905b4e9a6658ad0ec7d11429e" ON "course_enrollments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e905b4e9a6658ad0ec7d11429e" ON "course_enrollments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d77e489db35c7d325700d799be" ON "course_enrollments" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab72c7fa06784137e905f1f8b8" ON "course_enrollments" ("userId") `);
        await queryRunner.query(`CREATE TABLE "courses" ("id" varchar PRIMARY KEY NOT NULL, "title" varchar(200) NOT NULL, "description" text NOT NULL, "summary" text, "thumbnailUrl" varchar(500), "category" varchar(100) NOT NULL, "tags" text NOT NULL DEFAULT ('[]'), "level" varchar(20) NOT NULL DEFAULT ('beginner'), "estimatedDuration" decimal(5,2), "language" varchar(5) NOT NULL DEFAULT ('en'), "instructorId" varchar NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('draft'), "pricing" text NOT NULL DEFAULT ('{"type":"free","price":0,"currency":"USD"}'), "enrollmentSettings" text NOT NULL DEFAULT ('{"isOpen":true,"maxEnrollments":null,"enrollmentDeadline":null}'), "prerequisites" text NOT NULL DEFAULT ('[]'), "learningObjectives" text NOT NULL DEFAULT ('[]'), "enrollmentCount" integer NOT NULL DEFAULT (0), "averageRating" decimal(3,2) NOT NULL DEFAULT (0), "ratingCount" integer NOT NULL DEFAULT (0), "completionRate" decimal(5,2) NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "publishedAt" datetime, "archivedAt" datetime)`);
        await queryRunner.query(`CREATE INDEX "IDX_a01a7f0e38c6f16024d16058ab" ON "courses" ("title") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ac2924c6479e5fa4fc5d1eec9" ON "courses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6714597bea722629fa7d32124" ON "courses" ("instructorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_889f2701163f86b2faf62a6247" ON "courses" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6714597bea722629fa7d32124" ON "courses" ("instructorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_889f2701163f86b2faf62a6247" ON "courses" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ac2924c6479e5fa4fc5d1eec9" ON "courses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_a01a7f0e38c6f16024d16058ab" ON "courses" ("title") `);
        await queryRunner.query(`CREATE TABLE "lessons" ("id" varchar PRIMARY KEY NOT NULL, "title" varchar(200) NOT NULL, "description" text, "content" text, "contentType" varchar(20) NOT NULL DEFAULT ('text'), "order" integer NOT NULL, "durationMinutes" integer, "level" varchar(20) NOT NULL DEFAULT ('beginner'), "videoUrl" varchar(500), "videoDuration" integer, "resources" text NOT NULL DEFAULT ('[]'), "learningObjectives" text NOT NULL DEFAULT ('[]'), "keyConcepts" text NOT NULL DEFAULT ('[]'), "status" varchar(20) NOT NULL DEFAULT ('draft'), "accessSettings" text NOT NULL DEFAULT ('{"isPreview":false,"requiresEnrollment":true,"prerequisiteCompleted":false}'), "prerequisites" text NOT NULL DEFAULT ('[]'), "completionCount" integer NOT NULL DEFAULT (0), "averageTimeSpent" decimal(8,2) NOT NULL DEFAULT (0), "engagementScore" decimal(5,2) NOT NULL DEFAULT (0), "courseId" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "publishedAt" datetime)`);
        await queryRunner.query(`CREATE INDEX "IDX_633a748d9720d4c3c25f0fc120" ON "lessons" ("order") `);
        await queryRunner.query(`CREATE INDEX "IDX_913c2193a312392325ec82ea21" ON "lessons" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a9ff2409a84c76560ae8a9259" ON "lessons" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_913c2193a312392325ec82ea21" ON "lessons" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_633a748d9720d4c3c25f0fc120" ON "lessons" ("order") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a9ff2409a84c76560ae8a9259" ON "lessons" ("courseId") `);
        await queryRunner.query(`CREATE TABLE "user_progress" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "lessonId" varchar NOT NULL, "isCompleted" boolean NOT NULL DEFAULT (0), "progressPercentage" decimal(5,2) NOT NULL DEFAULT (0), "currentPosition" decimal(10,2) NOT NULL DEFAULT (0), "timeSpentMinutes" decimal(10,2) NOT NULL DEFAULT (0), "visitCount" integer NOT NULL DEFAULT (0), "startedAt" datetime, "completedAt" datetime, "lastAccessedAt" datetime, "engagementScore" decimal(5,2) NOT NULL DEFAULT (0), "reviewCount" integer NOT NULL DEFAULT (0), "difficultyRating" integer, "userRating" integer, "notes" text, "metadata" text NOT NULL DEFAULT ('{}'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_30e04e705c2aae1fa3856f9028e" UNIQUE ("userId", "lessonId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b5d0e1b57bc6c761fb49e79bf8" ON "user_progress" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b68ae6c7bbd71b00257277c42f" ON "user_progress" ("lessonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_914febf8e62745430f8a313e14" ON "user_progress" ("isCompleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_5626e741b756134daedbcd4ecf" ON "user_progress" ("completedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_914febf8e62745430f8a313e14" ON "user_progress" ("isCompleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_5626e741b756134daedbcd4ecf" ON "user_progress" ("completedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_b68ae6c7bbd71b00257277c42f" ON "user_progress" ("lessonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5d0e1b57bc6c761fb49e79bf8" ON "user_progress" ("userId") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "tokenHash" varchar(255) NOT NULL, "userId" varchar NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "revokedAt" datetime, "revocationReason" varchar(100), "userAgent" varchar(500), "ipAddress" varchar(45), "deviceName" varchar(100), "lastUsedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c25bc63d248ca90e8dcc1d92d06" UNIQUE ("tokenHash"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e59cfb4ce9deac3c9411eaa0e0" ON "refresh_tokens" ("userId", "isRevoked") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c25bc63d248ca90e8dcc1d92d0" ON "refresh_tokens" ("tokenHash") `);
        await queryRunner.query(`DROP INDEX "IDX_ab72c7fa06784137e905f1f8b8"`);
        await queryRunner.query(`DROP INDEX "IDX_d77e489db35c7d325700d799be"`);
        await queryRunner.query(`DROP INDEX "IDX_e905b4e9a6658ad0ec7d11429e"`);
        await queryRunner.query(`DROP INDEX "IDX_e905b4e9a6658ad0ec7d11429e"`);
        await queryRunner.query(`DROP INDEX "IDX_d77e489db35c7d325700d799be"`);
        await queryRunner.query(`DROP INDEX "IDX_ab72c7fa06784137e905f1f8b8"`);
        await queryRunner.query(`CREATE TABLE "temporary_course_enrollments" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "courseId" varchar NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('active'), "enrollmentMethod" varchar(20) NOT NULL DEFAULT ('self'), "progressPercentage" decimal(5,2) NOT NULL DEFAULT (0), "lessonsCompleted" integer NOT NULL DEFAULT (0), "totalLessons" integer NOT NULL DEFAULT (0), "timeSpentMinutes" decimal(10,2) NOT NULL DEFAULT (0), "lastAccessedLessonId" varchar, "currentLessonId" varchar, "isCompleted" boolean NOT NULL DEFAULT (0), "completedAt" datetime, "finalScore" decimal(5,2), "isCertificateEligible" boolean NOT NULL DEFAULT (0), "certificateIssuedAt" datetime, "paymentStatus" varchar(20) NOT NULL DEFAULT ('free'), "paymentAmount" decimal(10,2) NOT NULL DEFAULT (0), "paymentCurrency" varchar(3) NOT NULL DEFAULT ('USD'), "paymentTransactionId" varchar, "expiresAt" datetime, "accessNotes" text, "lastActivityAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "startedAt" datetime, "suspendedAt" datetime, "droppedAt" datetime, CONSTRAINT "UQ_03317be27c60a610b6a28795525" UNIQUE ("userId", "courseId"), CONSTRAINT "FK_ab72c7fa06784137e905f1f8b8e" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_d77e489db35c7d325700d799be6" FOREIGN KEY ("courseId") REFERENCES "courses" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_course_enrollments"("id", "userId", "courseId", "status", "enrollmentMethod", "progressPercentage", "lessonsCompleted", "totalLessons", "timeSpentMinutes", "lastAccessedLessonId", "currentLessonId", "isCompleted", "completedAt", "finalScore", "isCertificateEligible", "certificateIssuedAt", "paymentStatus", "paymentAmount", "paymentCurrency", "paymentTransactionId", "expiresAt", "accessNotes", "lastActivityAt", "createdAt", "updatedAt", "startedAt", "suspendedAt", "droppedAt") SELECT "id", "userId", "courseId", "status", "enrollmentMethod", "progressPercentage", "lessonsCompleted", "totalLessons", "timeSpentMinutes", "lastAccessedLessonId", "currentLessonId", "isCompleted", "completedAt", "finalScore", "isCertificateEligible", "certificateIssuedAt", "paymentStatus", "paymentAmount", "paymentCurrency", "paymentTransactionId", "expiresAt", "accessNotes", "lastActivityAt", "createdAt", "updatedAt", "startedAt", "suspendedAt", "droppedAt" FROM "course_enrollments"`);
        await queryRunner.query(`DROP TABLE "course_enrollments"`);
        await queryRunner.query(`ALTER TABLE "temporary_course_enrollments" RENAME TO "course_enrollments"`);
        await queryRunner.query(`CREATE INDEX "IDX_ab72c7fa06784137e905f1f8b8" ON "course_enrollments" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d77e489db35c7d325700d799be" ON "course_enrollments" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e905b4e9a6658ad0ec7d11429e" ON "course_enrollments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e905b4e9a6658ad0ec7d11429e" ON "course_enrollments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d77e489db35c7d325700d799be" ON "course_enrollments" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab72c7fa06784137e905f1f8b8" ON "course_enrollments" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_a01a7f0e38c6f16024d16058ab"`);
        await queryRunner.query(`DROP INDEX "IDX_1ac2924c6479e5fa4fc5d1eec9"`);
        await queryRunner.query(`DROP INDEX "IDX_e6714597bea722629fa7d32124"`);
        await queryRunner.query(`DROP INDEX "IDX_889f2701163f86b2faf62a6247"`);
        await queryRunner.query(`DROP INDEX "IDX_e6714597bea722629fa7d32124"`);
        await queryRunner.query(`DROP INDEX "IDX_889f2701163f86b2faf62a6247"`);
        await queryRunner.query(`DROP INDEX "IDX_1ac2924c6479e5fa4fc5d1eec9"`);
        await queryRunner.query(`DROP INDEX "IDX_a01a7f0e38c6f16024d16058ab"`);
        await queryRunner.query(`CREATE TABLE "temporary_courses" ("id" varchar PRIMARY KEY NOT NULL, "title" varchar(200) NOT NULL, "description" text NOT NULL, "summary" text, "thumbnailUrl" varchar(500), "category" varchar(100) NOT NULL, "tags" text NOT NULL DEFAULT ('[]'), "level" varchar(20) NOT NULL DEFAULT ('beginner'), "estimatedDuration" decimal(5,2), "language" varchar(5) NOT NULL DEFAULT ('en'), "instructorId" varchar NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('draft'), "pricing" text NOT NULL DEFAULT ('{"type":"free","price":0,"currency":"USD"}'), "enrollmentSettings" text NOT NULL DEFAULT ('{"isOpen":true,"maxEnrollments":null,"enrollmentDeadline":null}'), "prerequisites" text NOT NULL DEFAULT ('[]'), "learningObjectives" text NOT NULL DEFAULT ('[]'), "enrollmentCount" integer NOT NULL DEFAULT (0), "averageRating" decimal(3,2) NOT NULL DEFAULT (0), "ratingCount" integer NOT NULL DEFAULT (0), "completionRate" decimal(5,2) NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "publishedAt" datetime, "archivedAt" datetime, CONSTRAINT "FK_e6714597bea722629fa7d32124a" FOREIGN KEY ("instructorId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_courses"("id", "title", "description", "summary", "thumbnailUrl", "category", "tags", "level", "estimatedDuration", "language", "instructorId", "status", "pricing", "enrollmentSettings", "prerequisites", "learningObjectives", "enrollmentCount", "averageRating", "ratingCount", "completionRate", "createdAt", "updatedAt", "publishedAt", "archivedAt") SELECT "id", "title", "description", "summary", "thumbnailUrl", "category", "tags", "level", "estimatedDuration", "language", "instructorId", "status", "pricing", "enrollmentSettings", "prerequisites", "learningObjectives", "enrollmentCount", "averageRating", "ratingCount", "completionRate", "createdAt", "updatedAt", "publishedAt", "archivedAt" FROM "courses"`);
        await queryRunner.query(`DROP TABLE "courses"`);
        await queryRunner.query(`ALTER TABLE "temporary_courses" RENAME TO "courses"`);
        await queryRunner.query(`CREATE INDEX "IDX_a01a7f0e38c6f16024d16058ab" ON "courses" ("title") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ac2924c6479e5fa4fc5d1eec9" ON "courses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6714597bea722629fa7d32124" ON "courses" ("instructorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_889f2701163f86b2faf62a6247" ON "courses" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6714597bea722629fa7d32124" ON "courses" ("instructorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_889f2701163f86b2faf62a6247" ON "courses" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ac2924c6479e5fa4fc5d1eec9" ON "courses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_a01a7f0e38c6f16024d16058ab" ON "courses" ("title") `);
        await queryRunner.query(`DROP INDEX "IDX_633a748d9720d4c3c25f0fc120"`);
        await queryRunner.query(`DROP INDEX "IDX_913c2193a312392325ec82ea21"`);
        await queryRunner.query(`DROP INDEX "IDX_1a9ff2409a84c76560ae8a9259"`);
        await queryRunner.query(`DROP INDEX "IDX_913c2193a312392325ec82ea21"`);
        await queryRunner.query(`DROP INDEX "IDX_633a748d9720d4c3c25f0fc120"`);
        await queryRunner.query(`DROP INDEX "IDX_1a9ff2409a84c76560ae8a9259"`);
        await queryRunner.query(`CREATE TABLE "temporary_lessons" ("id" varchar PRIMARY KEY NOT NULL, "title" varchar(200) NOT NULL, "description" text, "content" text, "contentType" varchar(20) NOT NULL DEFAULT ('text'), "order" integer NOT NULL, "durationMinutes" integer, "level" varchar(20) NOT NULL DEFAULT ('beginner'), "videoUrl" varchar(500), "videoDuration" integer, "resources" text NOT NULL DEFAULT ('[]'), "learningObjectives" text NOT NULL DEFAULT ('[]'), "keyConcepts" text NOT NULL DEFAULT ('[]'), "status" varchar(20) NOT NULL DEFAULT ('draft'), "accessSettings" text NOT NULL DEFAULT ('{"isPreview":false,"requiresEnrollment":true,"prerequisiteCompleted":false}'), "prerequisites" text NOT NULL DEFAULT ('[]'), "completionCount" integer NOT NULL DEFAULT (0), "averageTimeSpent" decimal(8,2) NOT NULL DEFAULT (0), "engagementScore" decimal(5,2) NOT NULL DEFAULT (0), "courseId" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "publishedAt" datetime, CONSTRAINT "FK_1a9ff2409a84c76560ae8a92590" FOREIGN KEY ("courseId") REFERENCES "courses" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_lessons"("id", "title", "description", "content", "contentType", "order", "durationMinutes", "level", "videoUrl", "videoDuration", "resources", "learningObjectives", "keyConcepts", "status", "accessSettings", "prerequisites", "completionCount", "averageTimeSpent", "engagementScore", "courseId", "createdAt", "updatedAt", "publishedAt") SELECT "id", "title", "description", "content", "contentType", "order", "durationMinutes", "level", "videoUrl", "videoDuration", "resources", "learningObjectives", "keyConcepts", "status", "accessSettings", "prerequisites", "completionCount", "averageTimeSpent", "engagementScore", "courseId", "createdAt", "updatedAt", "publishedAt" FROM "lessons"`);
        await queryRunner.query(`DROP TABLE "lessons"`);
        await queryRunner.query(`ALTER TABLE "temporary_lessons" RENAME TO "lessons"`);
        await queryRunner.query(`CREATE INDEX "IDX_633a748d9720d4c3c25f0fc120" ON "lessons" ("order") `);
        await queryRunner.query(`CREATE INDEX "IDX_913c2193a312392325ec82ea21" ON "lessons" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a9ff2409a84c76560ae8a9259" ON "lessons" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_913c2193a312392325ec82ea21" ON "lessons" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_633a748d9720d4c3c25f0fc120" ON "lessons" ("order") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a9ff2409a84c76560ae8a9259" ON "lessons" ("courseId") `);
        await queryRunner.query(`DROP INDEX "IDX_b5d0e1b57bc6c761fb49e79bf8"`);
        await queryRunner.query(`DROP INDEX "IDX_b68ae6c7bbd71b00257277c42f"`);
        await queryRunner.query(`DROP INDEX "IDX_914febf8e62745430f8a313e14"`);
        await queryRunner.query(`DROP INDEX "IDX_5626e741b756134daedbcd4ecf"`);
        await queryRunner.query(`DROP INDEX "IDX_914febf8e62745430f8a313e14"`);
        await queryRunner.query(`DROP INDEX "IDX_5626e741b756134daedbcd4ecf"`);
        await queryRunner.query(`DROP INDEX "IDX_b68ae6c7bbd71b00257277c42f"`);
        await queryRunner.query(`DROP INDEX "IDX_b5d0e1b57bc6c761fb49e79bf8"`);
        await queryRunner.query(`CREATE TABLE "temporary_user_progress" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "lessonId" varchar NOT NULL, "isCompleted" boolean NOT NULL DEFAULT (0), "progressPercentage" decimal(5,2) NOT NULL DEFAULT (0), "currentPosition" decimal(10,2) NOT NULL DEFAULT (0), "timeSpentMinutes" decimal(10,2) NOT NULL DEFAULT (0), "visitCount" integer NOT NULL DEFAULT (0), "startedAt" datetime, "completedAt" datetime, "lastAccessedAt" datetime, "engagementScore" decimal(5,2) NOT NULL DEFAULT (0), "reviewCount" integer NOT NULL DEFAULT (0), "difficultyRating" integer, "userRating" integer, "notes" text, "metadata" text NOT NULL DEFAULT ('{}'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_30e04e705c2aae1fa3856f9028e" UNIQUE ("userId", "lessonId"), CONSTRAINT "FK_b5d0e1b57bc6c761fb49e79bf89" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_b68ae6c7bbd71b00257277c42f8" FOREIGN KEY ("lessonId") REFERENCES "lessons" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_user_progress"("id", "userId", "lessonId", "isCompleted", "progressPercentage", "currentPosition", "timeSpentMinutes", "visitCount", "startedAt", "completedAt", "lastAccessedAt", "engagementScore", "reviewCount", "difficultyRating", "userRating", "notes", "metadata", "createdAt", "updatedAt") SELECT "id", "userId", "lessonId", "isCompleted", "progressPercentage", "currentPosition", "timeSpentMinutes", "visitCount", "startedAt", "completedAt", "lastAccessedAt", "engagementScore", "reviewCount", "difficultyRating", "userRating", "notes", "metadata", "createdAt", "updatedAt" FROM "user_progress"`);
        await queryRunner.query(`DROP TABLE "user_progress"`);
        await queryRunner.query(`ALTER TABLE "temporary_user_progress" RENAME TO "user_progress"`);
        await queryRunner.query(`CREATE INDEX "IDX_b5d0e1b57bc6c761fb49e79bf8" ON "user_progress" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b68ae6c7bbd71b00257277c42f" ON "user_progress" ("lessonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_914febf8e62745430f8a313e14" ON "user_progress" ("isCompleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_5626e741b756134daedbcd4ecf" ON "user_progress" ("completedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_914febf8e62745430f8a313e14" ON "user_progress" ("isCompleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_5626e741b756134daedbcd4ecf" ON "user_progress" ("completedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_b68ae6c7bbd71b00257277c42f" ON "user_progress" ("lessonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5d0e1b57bc6c761fb49e79bf8" ON "user_progress" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_e59cfb4ce9deac3c9411eaa0e0"`);
        await queryRunner.query(`DROP INDEX "IDX_c25bc63d248ca90e8dcc1d92d0"`);
        await queryRunner.query(`CREATE TABLE "temporary_refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "tokenHash" varchar(255) NOT NULL, "userId" varchar NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "revokedAt" datetime, "revocationReason" varchar(100), "userAgent" varchar(500), "ipAddress" varchar(45), "deviceName" varchar(100), "lastUsedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c25bc63d248ca90e8dcc1d92d06" UNIQUE ("tokenHash"), CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_refresh_tokens"("id", "tokenHash", "userId", "expiresAt", "isRevoked", "revokedAt", "revocationReason", "userAgent", "ipAddress", "deviceName", "lastUsedAt", "createdAt") SELECT "id", "tokenHash", "userId", "expiresAt", "isRevoked", "revokedAt", "revocationReason", "userAgent", "ipAddress", "deviceName", "lastUsedAt", "createdAt" FROM "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`ALTER TABLE "temporary_refresh_tokens" RENAME TO "refresh_tokens"`);
        await queryRunner.query(`CREATE INDEX "IDX_e59cfb4ce9deac3c9411eaa0e0" ON "refresh_tokens" ("userId", "isRevoked") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c25bc63d248ca90e8dcc1d92d0" ON "refresh_tokens" ("tokenHash") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_c25bc63d248ca90e8dcc1d92d0"`);
        await queryRunner.query(`DROP INDEX "IDX_e59cfb4ce9deac3c9411eaa0e0"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" RENAME TO "temporary_refresh_tokens"`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "tokenHash" varchar(255) NOT NULL, "userId" varchar NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "revokedAt" datetime, "revocationReason" varchar(100), "userAgent" varchar(500), "ipAddress" varchar(45), "deviceName" varchar(100), "lastUsedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c25bc63d248ca90e8dcc1d92d06" UNIQUE ("tokenHash"))`);
        await queryRunner.query(`INSERT INTO "refresh_tokens"("id", "tokenHash", "userId", "expiresAt", "isRevoked", "revokedAt", "revocationReason", "userAgent", "ipAddress", "deviceName", "lastUsedAt", "createdAt") SELECT "id", "tokenHash", "userId", "expiresAt", "isRevoked", "revokedAt", "revocationReason", "userAgent", "ipAddress", "deviceName", "lastUsedAt", "createdAt" FROM "temporary_refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "temporary_refresh_tokens"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c25bc63d248ca90e8dcc1d92d0" ON "refresh_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_e59cfb4ce9deac3c9411eaa0e0" ON "refresh_tokens" ("userId", "isRevoked") `);
        await queryRunner.query(`DROP INDEX "IDX_b5d0e1b57bc6c761fb49e79bf8"`);
        await queryRunner.query(`DROP INDEX "IDX_b68ae6c7bbd71b00257277c42f"`);
        await queryRunner.query(`DROP INDEX "IDX_5626e741b756134daedbcd4ecf"`);
        await queryRunner.query(`DROP INDEX "IDX_914febf8e62745430f8a313e14"`);
        await queryRunner.query(`DROP INDEX "IDX_5626e741b756134daedbcd4ecf"`);
        await queryRunner.query(`DROP INDEX "IDX_914febf8e62745430f8a313e14"`);
        await queryRunner.query(`DROP INDEX "IDX_b68ae6c7bbd71b00257277c42f"`);
        await queryRunner.query(`DROP INDEX "IDX_b5d0e1b57bc6c761fb49e79bf8"`);
        await queryRunner.query(`ALTER TABLE "user_progress" RENAME TO "temporary_user_progress"`);
        await queryRunner.query(`CREATE TABLE "user_progress" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "lessonId" varchar NOT NULL, "isCompleted" boolean NOT NULL DEFAULT (0), "progressPercentage" decimal(5,2) NOT NULL DEFAULT (0), "currentPosition" decimal(10,2) NOT NULL DEFAULT (0), "timeSpentMinutes" decimal(10,2) NOT NULL DEFAULT (0), "visitCount" integer NOT NULL DEFAULT (0), "startedAt" datetime, "completedAt" datetime, "lastAccessedAt" datetime, "engagementScore" decimal(5,2) NOT NULL DEFAULT (0), "reviewCount" integer NOT NULL DEFAULT (0), "difficultyRating" integer, "userRating" integer, "notes" text, "metadata" text NOT NULL DEFAULT ('{}'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_30e04e705c2aae1fa3856f9028e" UNIQUE ("userId", "lessonId"))`);
        await queryRunner.query(`INSERT INTO "user_progress"("id", "userId", "lessonId", "isCompleted", "progressPercentage", "currentPosition", "timeSpentMinutes", "visitCount", "startedAt", "completedAt", "lastAccessedAt", "engagementScore", "reviewCount", "difficultyRating", "userRating", "notes", "metadata", "createdAt", "updatedAt") SELECT "id", "userId", "lessonId", "isCompleted", "progressPercentage", "currentPosition", "timeSpentMinutes", "visitCount", "startedAt", "completedAt", "lastAccessedAt", "engagementScore", "reviewCount", "difficultyRating", "userRating", "notes", "metadata", "createdAt", "updatedAt" FROM "temporary_user_progress"`);
        await queryRunner.query(`DROP TABLE "temporary_user_progress"`);
        await queryRunner.query(`CREATE INDEX "IDX_b5d0e1b57bc6c761fb49e79bf8" ON "user_progress" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b68ae6c7bbd71b00257277c42f" ON "user_progress" ("lessonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5626e741b756134daedbcd4ecf" ON "user_progress" ("completedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_914febf8e62745430f8a313e14" ON "user_progress" ("isCompleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_5626e741b756134daedbcd4ecf" ON "user_progress" ("completedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_914febf8e62745430f8a313e14" ON "user_progress" ("isCompleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_b68ae6c7bbd71b00257277c42f" ON "user_progress" ("lessonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5d0e1b57bc6c761fb49e79bf8" ON "user_progress" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_1a9ff2409a84c76560ae8a9259"`);
        await queryRunner.query(`DROP INDEX "IDX_633a748d9720d4c3c25f0fc120"`);
        await queryRunner.query(`DROP INDEX "IDX_913c2193a312392325ec82ea21"`);
        await queryRunner.query(`DROP INDEX "IDX_1a9ff2409a84c76560ae8a9259"`);
        await queryRunner.query(`DROP INDEX "IDX_913c2193a312392325ec82ea21"`);
        await queryRunner.query(`DROP INDEX "IDX_633a748d9720d4c3c25f0fc120"`);
        await queryRunner.query(`ALTER TABLE "lessons" RENAME TO "temporary_lessons"`);
        await queryRunner.query(`CREATE TABLE "lessons" ("id" varchar PRIMARY KEY NOT NULL, "title" varchar(200) NOT NULL, "description" text, "content" text, "contentType" varchar(20) NOT NULL DEFAULT ('text'), "order" integer NOT NULL, "durationMinutes" integer, "level" varchar(20) NOT NULL DEFAULT ('beginner'), "videoUrl" varchar(500), "videoDuration" integer, "resources" text NOT NULL DEFAULT ('[]'), "learningObjectives" text NOT NULL DEFAULT ('[]'), "keyConcepts" text NOT NULL DEFAULT ('[]'), "status" varchar(20) NOT NULL DEFAULT ('draft'), "accessSettings" text NOT NULL DEFAULT ('{"isPreview":false,"requiresEnrollment":true,"prerequisiteCompleted":false}'), "prerequisites" text NOT NULL DEFAULT ('[]'), "completionCount" integer NOT NULL DEFAULT (0), "averageTimeSpent" decimal(8,2) NOT NULL DEFAULT (0), "engagementScore" decimal(5,2) NOT NULL DEFAULT (0), "courseId" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "publishedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "lessons"("id", "title", "description", "content", "contentType", "order", "durationMinutes", "level", "videoUrl", "videoDuration", "resources", "learningObjectives", "keyConcepts", "status", "accessSettings", "prerequisites", "completionCount", "averageTimeSpent", "engagementScore", "courseId", "createdAt", "updatedAt", "publishedAt") SELECT "id", "title", "description", "content", "contentType", "order", "durationMinutes", "level", "videoUrl", "videoDuration", "resources", "learningObjectives", "keyConcepts", "status", "accessSettings", "prerequisites", "completionCount", "averageTimeSpent", "engagementScore", "courseId", "createdAt", "updatedAt", "publishedAt" FROM "temporary_lessons"`);
        await queryRunner.query(`DROP TABLE "temporary_lessons"`);
        await queryRunner.query(`CREATE INDEX "IDX_1a9ff2409a84c76560ae8a9259" ON "lessons" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_633a748d9720d4c3c25f0fc120" ON "lessons" ("order") `);
        await queryRunner.query(`CREATE INDEX "IDX_913c2193a312392325ec82ea21" ON "lessons" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a9ff2409a84c76560ae8a9259" ON "lessons" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_913c2193a312392325ec82ea21" ON "lessons" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_633a748d9720d4c3c25f0fc120" ON "lessons" ("order") `);
        await queryRunner.query(`DROP INDEX "IDX_a01a7f0e38c6f16024d16058ab"`);
        await queryRunner.query(`DROP INDEX "IDX_1ac2924c6479e5fa4fc5d1eec9"`);
        await queryRunner.query(`DROP INDEX "IDX_889f2701163f86b2faf62a6247"`);
        await queryRunner.query(`DROP INDEX "IDX_e6714597bea722629fa7d32124"`);
        await queryRunner.query(`DROP INDEX "IDX_889f2701163f86b2faf62a6247"`);
        await queryRunner.query(`DROP INDEX "IDX_e6714597bea722629fa7d32124"`);
        await queryRunner.query(`DROP INDEX "IDX_1ac2924c6479e5fa4fc5d1eec9"`);
        await queryRunner.query(`DROP INDEX "IDX_a01a7f0e38c6f16024d16058ab"`);
        await queryRunner.query(`ALTER TABLE "courses" RENAME TO "temporary_courses"`);
        await queryRunner.query(`CREATE TABLE "courses" ("id" varchar PRIMARY KEY NOT NULL, "title" varchar(200) NOT NULL, "description" text NOT NULL, "summary" text, "thumbnailUrl" varchar(500), "category" varchar(100) NOT NULL, "tags" text NOT NULL DEFAULT ('[]'), "level" varchar(20) NOT NULL DEFAULT ('beginner'), "estimatedDuration" decimal(5,2), "language" varchar(5) NOT NULL DEFAULT ('en'), "instructorId" varchar NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('draft'), "pricing" text NOT NULL DEFAULT ('{"type":"free","price":0,"currency":"USD"}'), "enrollmentSettings" text NOT NULL DEFAULT ('{"isOpen":true,"maxEnrollments":null,"enrollmentDeadline":null}'), "prerequisites" text NOT NULL DEFAULT ('[]'), "learningObjectives" text NOT NULL DEFAULT ('[]'), "enrollmentCount" integer NOT NULL DEFAULT (0), "averageRating" decimal(3,2) NOT NULL DEFAULT (0), "ratingCount" integer NOT NULL DEFAULT (0), "completionRate" decimal(5,2) NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "publishedAt" datetime, "archivedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "courses"("id", "title", "description", "summary", "thumbnailUrl", "category", "tags", "level", "estimatedDuration", "language", "instructorId", "status", "pricing", "enrollmentSettings", "prerequisites", "learningObjectives", "enrollmentCount", "averageRating", "ratingCount", "completionRate", "createdAt", "updatedAt", "publishedAt", "archivedAt") SELECT "id", "title", "description", "summary", "thumbnailUrl", "category", "tags", "level", "estimatedDuration", "language", "instructorId", "status", "pricing", "enrollmentSettings", "prerequisites", "learningObjectives", "enrollmentCount", "averageRating", "ratingCount", "completionRate", "createdAt", "updatedAt", "publishedAt", "archivedAt" FROM "temporary_courses"`);
        await queryRunner.query(`DROP TABLE "temporary_courses"`);
        await queryRunner.query(`CREATE INDEX "IDX_a01a7f0e38c6f16024d16058ab" ON "courses" ("title") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ac2924c6479e5fa4fc5d1eec9" ON "courses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_889f2701163f86b2faf62a6247" ON "courses" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6714597bea722629fa7d32124" ON "courses" ("instructorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_889f2701163f86b2faf62a6247" ON "courses" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6714597bea722629fa7d32124" ON "courses" ("instructorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ac2924c6479e5fa4fc5d1eec9" ON "courses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_a01a7f0e38c6f16024d16058ab" ON "courses" ("title") `);
        await queryRunner.query(`DROP INDEX "IDX_ab72c7fa06784137e905f1f8b8"`);
        await queryRunner.query(`DROP INDEX "IDX_d77e489db35c7d325700d799be"`);
        await queryRunner.query(`DROP INDEX "IDX_e905b4e9a6658ad0ec7d11429e"`);
        await queryRunner.query(`DROP INDEX "IDX_e905b4e9a6658ad0ec7d11429e"`);
        await queryRunner.query(`DROP INDEX "IDX_d77e489db35c7d325700d799be"`);
        await queryRunner.query(`DROP INDEX "IDX_ab72c7fa06784137e905f1f8b8"`);
        await queryRunner.query(`ALTER TABLE "course_enrollments" RENAME TO "temporary_course_enrollments"`);
        await queryRunner.query(`CREATE TABLE "course_enrollments" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "courseId" varchar NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('active'), "enrollmentMethod" varchar(20) NOT NULL DEFAULT ('self'), "progressPercentage" decimal(5,2) NOT NULL DEFAULT (0), "lessonsCompleted" integer NOT NULL DEFAULT (0), "totalLessons" integer NOT NULL DEFAULT (0), "timeSpentMinutes" decimal(10,2) NOT NULL DEFAULT (0), "lastAccessedLessonId" varchar, "currentLessonId" varchar, "isCompleted" boolean NOT NULL DEFAULT (0), "completedAt" datetime, "finalScore" decimal(5,2), "isCertificateEligible" boolean NOT NULL DEFAULT (0), "certificateIssuedAt" datetime, "paymentStatus" varchar(20) NOT NULL DEFAULT ('free'), "paymentAmount" decimal(10,2) NOT NULL DEFAULT (0), "paymentCurrency" varchar(3) NOT NULL DEFAULT ('USD'), "paymentTransactionId" varchar, "expiresAt" datetime, "accessNotes" text, "lastActivityAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "startedAt" datetime, "suspendedAt" datetime, "droppedAt" datetime, CONSTRAINT "UQ_03317be27c60a610b6a28795525" UNIQUE ("userId", "courseId"))`);
        await queryRunner.query(`INSERT INTO "course_enrollments"("id", "userId", "courseId", "status", "enrollmentMethod", "progressPercentage", "lessonsCompleted", "totalLessons", "timeSpentMinutes", "lastAccessedLessonId", "currentLessonId", "isCompleted", "completedAt", "finalScore", "isCertificateEligible", "certificateIssuedAt", "paymentStatus", "paymentAmount", "paymentCurrency", "paymentTransactionId", "expiresAt", "accessNotes", "lastActivityAt", "createdAt", "updatedAt", "startedAt", "suspendedAt", "droppedAt") SELECT "id", "userId", "courseId", "status", "enrollmentMethod", "progressPercentage", "lessonsCompleted", "totalLessons", "timeSpentMinutes", "lastAccessedLessonId", "currentLessonId", "isCompleted", "completedAt", "finalScore", "isCertificateEligible", "certificateIssuedAt", "paymentStatus", "paymentAmount", "paymentCurrency", "paymentTransactionId", "expiresAt", "accessNotes", "lastActivityAt", "createdAt", "updatedAt", "startedAt", "suspendedAt", "droppedAt" FROM "temporary_course_enrollments"`);
        await queryRunner.query(`DROP TABLE "temporary_course_enrollments"`);
        await queryRunner.query(`CREATE INDEX "IDX_ab72c7fa06784137e905f1f8b8" ON "course_enrollments" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d77e489db35c7d325700d799be" ON "course_enrollments" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e905b4e9a6658ad0ec7d11429e" ON "course_enrollments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e905b4e9a6658ad0ec7d11429e" ON "course_enrollments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d77e489db35c7d325700d799be" ON "course_enrollments" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab72c7fa06784137e905f1f8b8" ON "course_enrollments" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_c25bc63d248ca90e8dcc1d92d0"`);
        await queryRunner.query(`DROP INDEX "IDX_e59cfb4ce9deac3c9411eaa0e0"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "IDX_b5d0e1b57bc6c761fb49e79bf8"`);
        await queryRunner.query(`DROP INDEX "IDX_b68ae6c7bbd71b00257277c42f"`);
        await queryRunner.query(`DROP INDEX "IDX_5626e741b756134daedbcd4ecf"`);
        await queryRunner.query(`DROP INDEX "IDX_914febf8e62745430f8a313e14"`);
        await queryRunner.query(`DROP INDEX "IDX_5626e741b756134daedbcd4ecf"`);
        await queryRunner.query(`DROP INDEX "IDX_914febf8e62745430f8a313e14"`);
        await queryRunner.query(`DROP INDEX "IDX_b68ae6c7bbd71b00257277c42f"`);
        await queryRunner.query(`DROP INDEX "IDX_b5d0e1b57bc6c761fb49e79bf8"`);
        await queryRunner.query(`DROP TABLE "user_progress"`);
        await queryRunner.query(`DROP INDEX "IDX_1a9ff2409a84c76560ae8a9259"`);
        await queryRunner.query(`DROP INDEX "IDX_633a748d9720d4c3c25f0fc120"`);
        await queryRunner.query(`DROP INDEX "IDX_913c2193a312392325ec82ea21"`);
        await queryRunner.query(`DROP INDEX "IDX_1a9ff2409a84c76560ae8a9259"`);
        await queryRunner.query(`DROP INDEX "IDX_913c2193a312392325ec82ea21"`);
        await queryRunner.query(`DROP INDEX "IDX_633a748d9720d4c3c25f0fc120"`);
        await queryRunner.query(`DROP TABLE "lessons"`);
        await queryRunner.query(`DROP INDEX "IDX_a01a7f0e38c6f16024d16058ab"`);
        await queryRunner.query(`DROP INDEX "IDX_1ac2924c6479e5fa4fc5d1eec9"`);
        await queryRunner.query(`DROP INDEX "IDX_889f2701163f86b2faf62a6247"`);
        await queryRunner.query(`DROP INDEX "IDX_e6714597bea722629fa7d32124"`);
        await queryRunner.query(`DROP INDEX "IDX_889f2701163f86b2faf62a6247"`);
        await queryRunner.query(`DROP INDEX "IDX_e6714597bea722629fa7d32124"`);
        await queryRunner.query(`DROP INDEX "IDX_1ac2924c6479e5fa4fc5d1eec9"`);
        await queryRunner.query(`DROP INDEX "IDX_a01a7f0e38c6f16024d16058ab"`);
        await queryRunner.query(`DROP TABLE "courses"`);
        await queryRunner.query(`DROP INDEX "IDX_ab72c7fa06784137e905f1f8b8"`);
        await queryRunner.query(`DROP INDEX "IDX_d77e489db35c7d325700d799be"`);
        await queryRunner.query(`DROP INDEX "IDX_e905b4e9a6658ad0ec7d11429e"`);
        await queryRunner.query(`DROP INDEX "IDX_e905b4e9a6658ad0ec7d11429e"`);
        await queryRunner.query(`DROP INDEX "IDX_d77e489db35c7d325700d799be"`);
        await queryRunner.query(`DROP INDEX "IDX_ab72c7fa06784137e905f1f8b8"`);
        await queryRunner.query(`DROP TABLE "course_enrollments"`);
        await queryRunner.query(`DROP INDEX "IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "IDX_f169d18dc7fce81f4c20974fd0"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
